### ISSUE TITLE
RFC - Update `Configuration` to support new configuration fields

### ISSUE THREAD

**Issue by sophie-cluml** [petabi/oinq#58]
## Background
- `Node`s fields are changed in https://github.com/aicers/review-web/pull/95/files. To support setting/getting configs for the changed `Node` fields, we need to update `request::Configuration` struct. 
- The number of fields (including the number of the fields recursively) in `Node` in review-web will grow in the future. For example, crusher's configuration will be added to the `Node` sooner or later.

## Idea for update
- as-is
https://github.com/petabi/oinq/blob/main/src/request.rs#L45-L54

- to-be
```rust
#[derive(Debug, Deserialize, Serialize)]
pub enum Configs {
    Hog(HogConfig),
    Piglet(PigletConfig),
    Reconverge(ReconvergeConfig),
   // crusher coming soon
}

#[derive(Debug, Deserialize, Serialize)]
pub struct HogConfig {
    pub review_address: Option<SocketAddr>,
    pub giganto_address: Option<SocketAddr>,
    pub active_protocols: Option<Vec<String>>,
    pub active_sources: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct PigletConfig {
    pub review_address: Option<SocketAddr>,
    pub giganto_address: Option<SocketAddr>,
    pub log_options: Option<Vec<String>>,
    pub http_file_types: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct ReconvergeConfig {
    pub review_address: Option<SocketAddr>,
    pub giganto_address: Option<SocketAddr>,
}
```

- Main rationale behind this idea is that, configurations vary by modules. Change of Hog configuration will only call for a change of `HogConfig`, without calling for changes in other structs and modules.
- Suitability of using `Option` for the fields in each Config struct will be determined individually, in PRs.

**Comment by sophie-cluml** [comment]
@msk could you take a look and share your thoughts on this change?

By the way, https://github.com/petabi/oinq/pull/56 has the same motivation with this RFC, but with a different approach.
cc. @dayeon5470

**Comment by msk** [comment]
Thanks for the detailed RFC.

I'm on board with the general direction of modularizing the configuration. However, I'd like to understand more about the inclusion of `review_address` in each of the `Config` structs. Could you elaborate on the specific use cases for `review_address` across different configurations like `HogConfig`, `PigletConfig`, and `ReconvergeConfig`? Are there particular scenarios or functionalities that necessitate `review_address` to be changed while nodes are running?

**Comment by syncpark** [comment]
For the `HogConfig`, I think the `giganto_address` should be inserted like `ReconvergeConfig` or `PigletConfig`.

**Comment by msk** [comment]
Thank you for the clarification. With this context, I have no further comments regarding the protocol change itself.

As for the actual implementation of dynamic address updates in a distributed environment, the problem is not trivial and demands a well-thought-out strategy to manage configuration updates seamlessly across different clients. I recommend investigating existing client-server systems that have successfully implemented dynamic address updates. By studying their solutions and learning from their experiences, we can aim to avoid common pitfalls and adopt best practices that ensure a robust implementation.

**Comment by sehkone** [comment]
I recognize your concerns regarding the implementation and its potential consequences. The need to change the review address arose from a general requirement for users to have the capability to modify server ports for security reasons. As a result, changes to the IP address might not always be visible in the user interface. My point is that this strategy is not set in stone. I will continue to monitor everything we need to take into account and ensure you are kept informed.
